/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DateTime { 'timestamp' : bigint, 'timeZone' : string }
export interface EnvironmentalConditions {
  'temperature' : number,
  'transparency' : bigint,
  'bortleClass' : bigint,
  'seeing' : bigint,
  'windSpeed' : number,
  'humidity' : bigint,
}
export interface ExposureDetails {
  'duration' : number,
  'gain' : bigint,
  'filter' : string,
  'units' : string,
  'stackingFrames' : bigint,
}
export interface Location { 'name' : string }
export interface ObservingSession {
  'id' : number,
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'updatedAt' : bigint,
  'notes' : string,
  'targetName' : string,
  'targetType' : string,
  'conditions' : EnvironmentalConditions,
  'rating' : Rating,
  'exposureDetails' : ExposureDetails,
  'dateTime' : DateTime,
  'location' : Location,
}
export interface Rating { 'review' : [] | [string], 'value' : bigint }
export interface SessionStats {
  'uniqueTargets' : bigint,
  'averageRating' : number,
  'totalSessions' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSession' : ActorMethod<[ObservingSession], number>,
  'deleteSession' : ActorMethod<[number], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSession' : ActorMethod<[number], [] | [ObservingSession]>,
  'getSessions' : ActorMethod<[], Array<ObservingSession>>,
  'getStats' : ActorMethod<[], SessionStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSession' : ActorMethod<[number, ObservingSession], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];