/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EnvironmentalConditions = IDL.Record({
  'temperature' : IDL.Float64,
  'transparency' : IDL.Nat,
  'bortleClass' : IDL.Nat,
  'seeing' : IDL.Nat,
  'windSpeed' : IDL.Float64,
  'humidity' : IDL.Nat,
});
export const Rating = IDL.Record({
  'review' : IDL.Opt(IDL.Text),
  'value' : IDL.Nat,
});
export const ExposureDetails = IDL.Record({
  'duration' : IDL.Float64,
  'gain' : IDL.Nat,
  'filter' : IDL.Text,
  'units' : IDL.Text,
  'stackingFrames' : IDL.Nat,
});
export const DateTime = IDL.Record({
  'timestamp' : IDL.Int,
  'timeZone' : IDL.Text,
});
export const Location = IDL.Record({ 'name' : IDL.Text });
export const ObservingSession = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'targetName' : IDL.Text,
  'targetType' : IDL.Text,
  'conditions' : EnvironmentalConditions,
  'rating' : Rating,
  'exposureDetails' : ExposureDetails,
  'dateTime' : DateTime,
  'location' : Location,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SessionStats = IDL.Record({
  'uniqueTargets' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'totalSessions' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSession' : IDL.Func([ObservingSession], [IDL.Nat32], []),
  'deleteSession' : IDL.Func([IDL.Nat32], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([IDL.Nat32], [IDL.Opt(ObservingSession)], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(ObservingSession)], ['query']),
  'getStats' : IDL.Func([], [SessionStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSession' : IDL.Func([IDL.Nat32, ObservingSession], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EnvironmentalConditions = IDL.Record({
    'temperature' : IDL.Float64,
    'transparency' : IDL.Nat,
    'bortleClass' : IDL.Nat,
    'seeing' : IDL.Nat,
    'windSpeed' : IDL.Float64,
    'humidity' : IDL.Nat,
  });
  const Rating = IDL.Record({
    'review' : IDL.Opt(IDL.Text),
    'value' : IDL.Nat,
  });
  const ExposureDetails = IDL.Record({
    'duration' : IDL.Float64,
    'gain' : IDL.Nat,
    'filter' : IDL.Text,
    'units' : IDL.Text,
    'stackingFrames' : IDL.Nat,
  });
  const DateTime = IDL.Record({ 'timestamp' : IDL.Int, 'timeZone' : IDL.Text });
  const Location = IDL.Record({ 'name' : IDL.Text });
  const ObservingSession = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'targetName' : IDL.Text,
    'targetType' : IDL.Text,
    'conditions' : EnvironmentalConditions,
    'rating' : Rating,
    'exposureDetails' : ExposureDetails,
    'dateTime' : DateTime,
    'location' : Location,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SessionStats = IDL.Record({
    'uniqueTargets' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'totalSessions' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSession' : IDL.Func([ObservingSession], [IDL.Nat32], []),
    'deleteSession' : IDL.Func([IDL.Nat32], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func(
        [IDL.Nat32],
        [IDL.Opt(ObservingSession)],
        ['query'],
      ),
    'getSessions' : IDL.Func([], [IDL.Vec(ObservingSession)], ['query']),
    'getStats' : IDL.Func([], [SessionStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSession' : IDL.Func([IDL.Nat32, ObservingSession], [], []),
  });
};

export const init = ({ IDL }) => { return []; };